version: '3.6'

services:
  livearch:
    build:
      context: .
    volumes:
      - ./src:/usr/local/src/build/src
      - ./pkg:/var/cache/pacman/pkg
      - ./out:/usr/local/src/build/out
    tmpfs:
      - /run
      - /tmp
