#!/usr/bin/sh

build() {
	add_binary find
	add_binary xargs

	add_file /usr/share/livearch/init

#	add_runscript
	add_systemd_unit initrd-livearch.service

	cp -a /usr/local/src/build/patch $BUILDROOT/patch
}
