#!/bin/bash

mtime() {
	echo $(( $(date +'%s%N') / 1000000 ))
}

analyze() {
	mtime_start=$(mtime)
	$1
	mtime_end=$(mtime)

	echo "execution time (in millis): $(( mtime_end - mtime_start ))"
}

main() {
	echo -n -e 'Postinst:\n'
	analyze postinst.sh
	echo -n -e '\n'

	echo -n -e 'Hooks:\n'
	analyze posthooks.py
	echo -n -e '\n'
}

mount -t proc     none /proc
mount -t sysfs    none /sys
mount -t devtmpfs none /dev

source /usr/local/etc/livearch.d/config

main

umount /dev
umount /sys
umount /proc

exit 0
